[build]
dist = "dist"  # where to output the final files
public_url = "/"

[[copy-dir]]
source = "public"
destination = "public"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i style/tailwind1.css -o style/output.css"]
# [[proxy]]
# backend = "http://localhost:4943"
# insecure = true
